In [15]:
import re
import pandas as pd

In [16]:
f = open('WhatsApp Chat with Alpha squad 😎.txt','r',encoding='utf-8')

In [17]:
data = f.read()

In [18]:
print(data)

3/30/24, 18:16 - Pawan:
3/30/24, 18:18 - Diksha Joshi: Guys m apne new ghr m gye hu
3/30/24, 18:18 - Diksha Joshi: 😂😂😂
3/30/24, 18:18 - Diksha Joshi: To ma kuch bole ni pa re
3/30/24, 18:18 - Diksha Joshi: Wrna m bhut bolne k mne h
3/30/24, 18:19 - (Chandan): Dishaaa
3/30/24, 18:24 - Gaurav Joshi: <Media omitted>
3/30/24, 18:24 - Gaurav Joshi: <Media omitted>
3/30/24, 18:25 - Gaurav Joshi: <Media omitted>
3/30/24, 19:40 - Himani BTech : <Media omitted>
3/30/24, 19:40 - Himani BTech : <Media omitted>
3/30/24, 19:41 - Himani BTech : Oya parso ki photos bhejo
3/30/24, 19:41 - Himani BTech : Royal vali
3/30/24, 19:48 - (Chandan): This message was deleted
3/30/24, 19:48 - (Chandan): This message was deleted
3/30/24, 19:49 - Ritesh: Bhai sahab
3/30/24, 19:49 - Ritesh: Sahi hai
3/30/24, 19:54 - Kiran: Guys tum personally gye ho na to ye photoa bhi personally share kro☠️☠️
3/30/24, 19:54 - Diksha Joshi: Ye chandu dadi se kaho
3/30/24, 19:54 - Diksha Joshi: Ye grup to band tha ky hua phir😂😂
3/30/24, 19:55 - (Chandan): ?
3/30/24, 20:04 - Himani BTech : Owner na khol Diya vapas sa ...Pawan 😂😂
3/30/24, 20:33 - Gaurav Joshi: Beta yai sahi hum kya gyai
3/30/24, 20:33 - Gaurav Joshi: Screenshot mrai
3/30/24, 20:34 - Himani BTech : Konsi language mai bol reha hai ba ... samajh ni ara
3/30/24, 20:35 - Gaurav Joshi: Kux nhi chd ab language bhi smj nhi ayagi
3/30/24, 20:37 - Himani BTech : Abe 🤣...ya kya bat hui
3/30/24, 20:37 - Gaurav Joshi: Nothing else
3/30/24, 20:37 - Himani BTech : Thik hogaya
3/30/24, 20:45 - Gaurav Joshi: Hmm
3/30/24, 20:50 - Gaurav Joshi: This message was deleted
3/30/24, 20:58 - (Chandan): This message was deleted
3/30/24, 20:58 - Himani BTech : Khuch bhi matlab...
3/30/24, 20:59 - Himani BTech : Aj to bhut Bakkar lag reha hai mujhe
3/30/24, 20:59 - Himani BTech : Roomate bhi ni ayi hai aur agar bagal bhi bhut Kam log hai
3/30/24, 20:59 - (Chandan): This message was deleted
3/30/24, 21:00 - (Chandan): Raat ghost na ayaae
3/30/24, 21:00 - Himani BTech : Hogaya bhyi tu so ja... jayada ghost mat kar 😐😐
3/30/24, 21:02 - Gaurav Joshi: Anshi kaha hai tere pram mitra
3/30/24, 21:02 - Himani BTech : Apne room pa
3/30/24, 21:03 - Himani BTech : Usna hair colour karvaya hai
3/30/24, 21:03 - Gaurav Joshi: Oh
3/30/24, 21:03 - Himani BTech : Yoo
3/30/24, 21:03 - Gaurav Joshi: Ab toh or axi lg rahi hogi
3/30/24, 21:03 - Himani BTech : Abe bhari 😂🤣
3/30/24, 21:03 - Gaurav Joshi: Nhi yrr
3/30/24, 21:03 - Himani BTech : Patani itna bakkawas colour ky karaya
3/30/24, 21:04 - (Chandan): This message was deleted
3/30/24, 21:04 - Gaurav Joshi: Asa mt bol
3/30/24, 21:04 - Himani BTech : Pink type ka
3/30/24, 21:04 - (Chandan): This message was deleted
3/30/24, 21:04 - Gaurav Joshi: Abe tum log kya jano yai colour vegera
3/30/24, 21:04 - Gaurav Joshi: Kitna axa lgta himani mere akho se dekh axa lgaiga😁
3/30/24, 21:04 - Himani BTech : Abe caremal karati to ak no lagta
3/30/24, 21:05 - Himani BTech : Ohhh
3/30/24, 21:05 - Himani BTech : 🤣😂
3/30/24, 21:05 - Gaurav Joshi: Yep
3/30/24, 21:05 - Himani BTech : This message was deleted
3/30/24, 21:06 - Gaurav Joshi: 😁😁
3/30/24, 21:06 - Gaurav Joshi: Kux nhi krr rahe thai
3/30/24, 21:06 - Himani BTech : Thik hogaya yr
3/30/24, 21:07 - Himani BTech : Net bhi khatam ho gaya hai mera ...aur pg ka wifi bhi kharab ho gaya hai
3/30/24, 21:08 - Gaurav Joshi: Sahi hai mai krr du recharge 😂
3/30/24, 21:08 - Himani BTech : Na yr ...
3/30/24, 21:08 - Himani BTech : I am an independent women
3/30/24, 21:08 - Gaurav Joshi: Chl
3/30/24, 21:08 - Gaurav Joshi: Be
3/30/24, 21:08 - Himani BTech : Bhale hi Ghar valo ka samne bheek mangi
3/30/24, 21:08 - (Chandan): Bol mat karde recharge
3/30/24, 21:08 - Himani BTech : Parde 😂😂😂😂
3/30/24, 21:09 - Gaurav Joshi: Independent women hai toh pocket money lena bnd krr de
3/30/24, 21:09 - Himani BTech : Puri bat to sun 😂😂
3/30/24, 21:09 - Himani BTech : Abe pura padhe
3/30/24, 21:09 - Gaurav Joshi: Oh that's a point
3/30/24, 21:09 - Himani BTech : Yesss
3/30/24, 21:09 - Himani BTech : Don't give sudden reactions
3/30/24, 21:10 - Gaurav Joshi: On the spot krta hu mai
3/30/24, 21:10 - Gaurav Joshi: Mag ka intezar nhi sidha reply
3/30/24, 21:10 - Himani BTech : Na na itna spontaneous ni hona chahiye
3/30/24, 21:11 - Himani BTech : Tabhi to ladki ni pat ri hai
3/30/24, 21:11 - Gaurav Joshi: Ab tumhari trah processor slow nhi hai
3/30/24, 21:11 - Gaurav Joshi: Msg*
3/30/24, 21:11 - Himani BTech : Ha ha ku ni 😂
3/30/24, 21:12 - Pawan: Ooe ye anshi hai kon
3/30/24, 21:12 - Gaurav Joshi: Mere crush
3/30/24, 21:12 - Gaurav Joshi: 😁
3/30/24, 21:13 - Himani BTech : Abhi last mai tujhe ak lardki dekhai thi video call pa...vahi
3/30/24, 21:13 - Pawan: Kab
3/30/24, 21:13 - Pawan: Mane ne deekha
3/30/24, 21:13 - Himani BTech : Bhut bardiya
3/30/24, 21:13 - Gaurav Joshi: Abe himani photo bhej de yrr
3/30/24, 21:13 - Himani BTech : Pagal hai kya
3/30/24, 21:13 - Gaurav Joshi: Wallpaper mai lagaunga
3/30/24, 21:14 - Gaurav Joshi: Apni or anshi ki
3/30/24, 21:14 - Gaurav Joshi: Bdd mai crop krkai tujhai hta dugha
3/30/24, 21:15 - Himani BTech : Ha beta yhi karega aur kar bhi kya Sakta hai
3/30/24, 21:15 - Gaurav Joshi: Hn phr
3/30/24, 21:16 - Gaurav Joshi:
3/30/24, 21:16 - Gaurav Joshi: 😂😁
3/30/24, 21:17 - Himani BTech : Ha re bhej di usa Maine 😂
3/30/24, 21:18 - Himani BTech :
3/30/24, 21:23 - Diksha Joshi: This message was deleted
3/30/24, 21:23 - Diksha Joshi: This message was deleted
3/30/24, 21:25 - Gaurav Joshi: Sahi hi Kiya
3/30/24, 21:26 - Gaurav Joshi:
3/30/24, 21:27 - Kiran: Ye duplicate nora fatehi kyu lgra😂🤡
3/30/24, 21:28 - Gaurav Joshi: Beta class ka don hai vo teacher bhi drtai hai
3/30/24, 21:28 - Gaurav Joshi: Issay
3/30/24, 21:28 - Ritesh: 💀💀💀💀💀
3/30/24, 21:28 - Ritesh: Bro
3/30/24, 21:29 - Ritesh: 🌚
3/30/24, 21:29 - Kiran: Vdeo dekh ke to ni lgra👽☠️
3/30/24, 21:29 - Diksha Joshi: 🥺😏
3/30/24, 21:29 - Gaurav Joshi: Look mai mtt
3/30/24, 21:29 - Kiran: Kon jaara
3/30/24, 21:29 - Kiran: M jaanti hu
3/30/24, 21:29 - Gaurav Joshi: 😁😁😁
3/30/24, 21:30 - Kiran: Mera hi padosi h😂
3/30/24, 21:31 - Gaurav Joshi: Oh axa
3/30/24, 21:59 - Pawan: Abe
4/2/24, 06:38 - Ritesh: Guys c mai paheli 2 unit he arahi hogi naa?
4/2/24, 06:38 - Ritesh: Ya class bhi arah hai?
4/2/24, 07:03 - Gaurav Joshi: 2.5
4/2/24, 19:17 - Ritesh: Guys
4/2/24, 19:17 - Ritesh: OS ke notes bhejdoo yaar
4/2/24, 19:17 - Ritesh: Pdf
4/2/24, 19:17 - Ritesh: Unit 1 and 2
4/2/24, 19:19 - Diksha Joshi: Kse bhej dk😂😂
4/2/24, 19:19 - Diksha Joshi: Banaye jo nii
4/2/24, 19:20 - Ritesh: Areey kuch bhi bhej doo padunga kaha se
4/2/24, 19:25 - Pawan: This message was deleted
4/2/24, 19:26 - Pawan: <Media omitted>
4/2/24, 19:32 - Ritesh: Syllabus to bhej doo
4/2/24, 19:42 - Gaurav Joshi: Computer system organisation
 computer system architecture
operating system structure
 operating system operations
 basic of process management
 storage management
protection and security
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - (Chandan): <Media omitted>
4/2/24, 19:43 - Gaurav Joshi: Threading
 multi core programming
 multi threading models
 thread library
 implicit esplicit
or threading problems
 process concept
process scheduling
 operations on process
 Inter process communication
 or IPCS system
4/2/24, 19:43 - Ritesh: Baas
4/2/24, 19:43 - Ritesh: Fk
4/2/24, 19:44 - Gaurav Joshi: H
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:47 - Piyush Ñegi: <Media omitted>
4/2/24, 19:50 - Ritesh: Toinks
4/2/24, 19:50 - Ritesh: Joo Banda uss teacher ki notes bana saktaa hai woo kuch bhi kaar saktaa hai life mai
4/2/24, 21:40 - Diksha Joshi: WAP of system call and define ?
What is the Operating system and explain its types?
Difference between multi-tasking and multi-programing?
Elaborate management process?
Explain multi-threading?
Process of management?
4/2/24, 21:40 - Diksha Joshi: Define the Threading problem and how can you fix those?
Describe thread libraries?
What is process scheduling?
How many types of operation are performed in processes explaining each one?
What are the examples of IPC system?
4/2/24, 21:40 - Diksha Joshi: Explain types of system call?
What are system call?
4/2/24, 21:40 - Diksha Joshi: Baki introduction to OS theory hai vo tum apne mn se likh sak tha ho
4/2/24, 21:40 - Diksha Joshi: Ye imp haa
4/3/24, 08:13 - Ritesh: This message was deleted
4/6/24, 14:01 - Himani BTech : Hlo BCA band ....b.tech band is back
4/6/24, 14:02 - Pawan: Hll
4/6/24, 14:02 - Piyush Ñegi: Hello
4/6/24, 14:02 - Himani BTech : Oh bhyi bhyi salu bhai
4/6/24, 14:02 - Himani BTech : First time Time reply
4/6/24, 14:03 - Himani BTech : Hiii
4/6/24, 14:03 - Pawan: Programming se fursat mil gae hai bal
4/6/24, 14:03 - Himani BTech : Vahi vahi 😂
4/6/24, 14:03 - Piyush Ñegi: Mil gaye
4/6/24, 14:03 - Pawan: Sale phone to utha
4/6/24, 14:03 - Pawan: Ka gf
4/6/24, 14:04 - Himani BTech : Thik hogaya phir kal nainital chal re ho ghumne sab
4/6/24, 14:04 - Piyush Ñegi: Window he corrupt ho gaye
4/6/24, 14:04 - Himani BTech : Abe 🤣😂
4/6/24, 14:08 - Piyush Ñegi: 🥹🥹🥹🥹🥹
4/6/24, 14:10 - Ritesh: Abe piyush
4/6/24, 14:10 - Ritesh: Tu baat bhi karta hai
4/6/24, 14:10 - Piyush Ñegi: Haa
4/6/24, 14:10 - Ritesh: <Media omitted>
4/6/24, 14:10 - Piyush Ñegi: Or tu bhe kar
4/6/24, 14:11 - Piyush Ñegi: ☠️☠️☠️☠️
4/6/24, 14:11 - Ritesh: Pakka pawan. Hai
4/6/24, 14:11 - Piyush Ñegi: Abe
4/6/24, 14:11 - Ritesh: Ye🤣
4/6/24, 14:11 - Piyush Ñegi: Nahi ha
4/6/24, 14:11 - Piyush Ñegi: You deleted this message
4/6/24, 14:12 - Piyush Ñegi: You deleted this message
4/6/24, 14:12 - Ritesh: 5.30
4/6/24, 14:12 - Piyush Ñegi: Okk
4/6/24, 14:14 - Himani BTech : Oya u people are supposed to answer this okay
4/6/24, 14:15 - Piyush Ñegi: Noo
4/6/24, 14:15 - Pawan: <Media omitted>
4/6/24, 14:15 - Piyush Ñegi: Jhut bol raha ha
4/6/24, 14:15 - Himani BTech : Thik hogaya matlab salu bhai is ready
4/6/24, 14:15 - Pawan: <Media omitted>
4/6/24, 14:16 - Piyush Ñegi: Naa
4/6/24, 14:16 - Piyush Ñegi: Just joking
4/6/24, 14:16 - Himani BTech : Salu bhai pitne vale hai aur khuch ni
4/6/24, 14:17 - Piyush Ñegi: kisse
4/6/24, 14:17 - Himani BTech : Ofcourse mujhse 🤣
4/6/24, 14:17 - Piyush Ñegi: Maf kar do dede
4/6/24, 14:17 - Piyush Ñegi: 🥹🥹🥹🥹
4/6/24, 14:18 - Himani BTech : Are are salu bhai ap mafi na mange 🤣
4/6/24, 14:18 - Piyush Ñegi: 😂😂😂
4/6/24, 14:19 - Piyush Ñegi: Pawan kha gaya
4/6/24, 14:19 - Himani BTech : So gaya vo ab
4/6/24, 14:19 - Piyush Ñegi: Accha
4/6/24, 14:19 - Pawan: Kuch b
4/6/24, 14:20 - Piyush Ñegi: Vahi to
4/6/24, 14:20 - Piyush Ñegi: Jhuti
4/6/24, 14:20 - Pawan: <Media omitted>
4/6/24, 14:21 - Piyush Ñegi: Sahi pakde Hai
4/6/24, 14:21 - Diksha Joshi: Piyush ke dady se batte
4/6/24, 14:21 - Diksha Joshi: Hue
4/6/24, 14:21 - Diksha Joshi: Meri aaj
4/6/24, 14:21 - Diksha Joshi: 😂😂
4/6/24, 14:21 - Diksha Joshi: Hai na piyush
4/6/24, 14:21 - Himani BTech : Oya diksha is back
4/6/24, 14:21 - Piyush Ñegi: Yess
4/6/24, 14:21 - Diksha Joshi: Diksha is going
M sleeping
4/6/24, 14:22 - Piyush Ñegi: Side ma baitha hua tha
4/6/24, 14:22 - Diksha Joshi: Piyush send address m aare kl😂😂
4/6/24, 14:22 - Diksha Joshi: Ha hash ra tha
4/6/24, 14:22 - Diksha Joshi: 😂😂
4/6/24, 14:22 - Himani BTech : Oya bata ba kal nainital chalegi
4/6/24, 14:22 - Diksha Joshi: Brooo
Mera pper pass h
4/6/24, 14:22 - Diksha Joshi: Abhi khi ni ghumnr
4/6/24, 14:22 - Diksha Joshi: 1 month baad contact plz
4/6/24, 14:22 - Himani BTech : Thik hogaya yr diksha thik hai
4/6/24, 14:23 - Diksha Joshi: Hihii😂😂
4/6/24, 14:23 - Himani BTech : Aj to hogaya 😏😏😏😏
4/6/24, 14:23 - Diksha Joshi: Ky ho gyaa
4/6/24, 14:23 - Diksha Joshi: Abe koi aur ni hora ky
4/6/24, 14:23 - Diksha Joshi: Tyyar
4/6/24, 14:23 - Himani BTech : Yahi dosti yahi pyar... abhinav style mai 🤣🤣🤣
4/6/24, 14:23 - Diksha Joshi: Chandu bhai to Hanuman dham gye h aj dp m dekhra
Hai na dadi
4/6/24, 14:23 - Piyush Ñegi: Chandan se puch o
4/6/24, 14:23 - Diksha Joshi: Ap abhinav ne hai na
4/6/24, 14:23 - Diksha Joshi: 😂
4/6/24, 14:24 - Diksha Joshi: Sallu bhai ppa ne bola ky ki aj whatsapp pr on rhna
4/6/24, 14:24 - Himani BTech : Vahi vahi
4/6/24, 14:24 - Diksha Joshi: Hihihi
4/6/24, 14:24 - Himani BTech : I also wanted the same answer
4/6/24, 14:24 - Diksha Joshi: Ya ap Pawan ke ghr gye ha
Aur uske hath h keyboard m
4/6/24, 14:24 - Diksha Joshi: For what question
4/6/24, 14:25 - Piyush Ñegi: Yes
4/6/24, 14:25 - Piyush Ñegi: Pawan he ha
4/6/24, 14:25 - Diksha Joshi: Dekha😂😂
4/6/24, 14:25 - Piyush Ñegi: Sahi pakde hai
4/6/24, 14:25 - Diksha Joshi: Ham to Nash nash se rubaru ha
4/6/24, 14:25 - Himani BTech : How salu bhai is typing
4/6/24, 14:25 - Diksha Joshi: Cauze he is replaced by
4/6/24, 14:25 - Himani BTech : Oh bhyi 😂
4/6/24, 14:25 - Diksha Joshi: Mr Pawan bhandari
4/6/24, 14:25 - Diksha Joshi: 😂
4/6/24, 14:25 - Himani BTech : Pawan dadi kaha 🤣🤣
4/6/24, 14:25 - Diksha Joshi: Ha ye ye
4/6/24, 14:26 - Piyush Ñegi: Chandan bhe kaha ha
4/6/24, 14:27 - Piyush Ñegi: Yad aati ha
4/6/24, 14:29 - Himani BTech : Bakki sab ki to na hogyi Jane ka liya to nirjala ma'am kya kehna chahinge
4/6/24, 14:29 - Diksha Joshi: Are chandu gaurav bchr h
4/6/24, 14:29 - Diksha Joshi: Avii
4/6/24, 14:29 - Diksha Joshi: Apko sbke sahmati sune chahiye
4/6/24, 14:30 - Himani BTech : Gaurav mana kar reha haj hai
4/6/24, 14:30 - Piyush Ñegi: Kon kon ha trip ma
4/6/24, 14:30 - Himani BTech : Jo ana chahe
4/6/24, 14:30 - Piyush Ñegi: Name plezz
4/6/24, 14:30 - Himani BTech : Ap kisko bulna chahte hai
4/6/24, 14:31 - Piyush Ñegi: Hamara hai hi Kaun
4/6/24, 14:31 - Diksha Joshi: Kb kra
4/6/24, 14:31 - Diksha Joshi: Kiraan😂😂
4/6/24, 14:31 - Himani BTech : Are Kiran bhi to hai 🤣🤣🤣🤣
4/6/24, 14:32 - Himani BTech : Usa to bhul hi gayi thi 🤣🤣
4/6/24, 14:32 - Piyush Ñegi: What
4/6/24, 14:32 - Pawan: Sahe bola
4/6/24, 14:32 - Himani BTech : Agla Sunday ko birthday hai ma'am ka
4/6/24, 14:32 - Pawan: Kiran programing b sikha dege
4/6/24, 14:33 - Diksha Joshi: Are ha m to bhul hi gye😂😂😂
4/6/24, 14:33 - Himani BTech : Are diksha personal chats u know
4/6/24, 14:33 - Himani BTech : Abe 🤣
4/6/24, 14:34 - Himani BTech : Sir bol re hai ki gadi ni hai ...kisma aunga
4/6/24, 14:34 - Piyush Ñegi: Jalve Hain Himani ji ke
4/6/24, 14:34 - Himani BTech : Are salu bhai aj itna kesa bolre hai ... mujhe khuch samajh ni ara
4/6/24, 14:34 - Himani BTech : 🧐
4/6/24, 14:34 - Himani BTech : Dal mai khuch to kala hai 😂
4/6/24, 14:35 - Piyush Ñegi: 😂😂😂😂😂
4/6/24, 14:35 - Piyush Ñegi: Puri dal hi Kali hai
4/6/24, 14:35 - Pawan: Daal pure he kale h
4/6/24, 14:35 - Diksha Joshi: Aare😂😂
4/6/24, 14:35 - Himani BTech : Na na ab yakeen ho gaya ki pawan aur salu bhai alag alag jah hai
4/6/24, 14:36 - Diksha Joshi: Na too ik hi jgh h
4/6/24, 14:36 - Pawan: Kya
4/6/24, 14:36 - Diksha Joshi: Ik hath m apna phn ik m saalu dadi ka
4/6/24, 14:36 - Himani BTech : Choti moti buses mai ni ate na sir isliye
4/6/24, 14:36 - Himani BTech : Na na
4/6/24, 14:36 - Piyush Ñegi: Haa
4/6/24, 14:36 - Pawan: <Media omitted>
4/6/24, 14:36 - Diksha Joshi: Aare uneh chahiye royal ik dum
4/6/24, 14:36 - Diksha Joshi: Ha ye piyush ka ghr ma
4/6/24, 14:36 - Pawan: Ye kahe se kahe tak lag raha hi salu bhi ka ghr
4/6/24, 14:36 - Piyush Ñegi: Me Ghar ke photo ha
4/6/24, 14:36 - Diksha Joshi: Kyuki Pawan ke room m
4/6/24, 14:36 - Himani BTech : Agar asa hota to dono mai alag alag likhta
4/6/24, 14:37 - Diksha Joshi: Ye design ni
4/6/24, 14:37 - Diksha Joshi: Ha
4/6/24, 14:37 - Diksha Joshi: Plane h😂😂😂😂
4/6/24, 14:37 - Himani BTech : Abe ni ba pawan new house mai shift ho gaya hai
4/6/24, 14:37 - Diksha Joshi: Are kab 😂😂
4/6/24, 14:37 - Himani BTech : Samjhe diksha
4/6/24, 14:37 - Himani BTech : Kab ke
4/6/24, 14:38 - Pawan: <Media omitted>
4/6/24, 14:38 - Himani BTech : Vahi to
4/6/24, 14:38 - Himani BTech : Ha re samajh gaya
4/6/24, 14:39 - Pawan: <Media omitted>
4/6/24, 14:39 - Gaurav Joshi: Abe yrr yai royal voyal kux nhi hn
4/6/24, 14:39 - Gaurav Joshi: Yahai se pehle bhimtal bus mai or phr nanital kitna lamba rsta hai
4/6/24, 14:39 - Himani BTech : <Media omitted>
4/6/24, 14:40 - Himani BTech : Abe tum direct nainital jaoge pagal
4/6/24, 14:40 - Himani BTech : Tum ku aoge bhimtal
4/6/24, 14:40 - Gaurav Joshi: Ab logo ko royal lg raha toh kya hi krr skta hu standard hi kux asa mera
4/6/24, 14:40 - Himani BTech : Chal chal hogaya😏😏😏
4/6/24, 14:41 - Pawan: <Media omitted>
4/6/24, 14:41 - Gaurav Joshi: Abe maine toh nhi bola jisne bola unse puxo
4/6/24, 14:41 - Pawan: <Media omitted>
4/6/24, 14:41 - Gaurav Joshi: Abe yai
4/6/24, 14:41 - Himani BTech : <Media omitted>
4/6/24, 14:42 - Gaurav Joshi: Suruvt kisnai ki bhai yai toh dekhna
4/6/24, 14:42 - Pawan: <Media omitted>
4/6/24, 14:42 - Himani BTech : Mai to thi na ...lakin 😏😏😏
4/6/24, 14:42 - Pawan: <Media omitted>
4/6/24, 14:42 - Gaurav Joshi: Bhai yrr asa kux nhi hai yrr kaha me lower middle class vala ldka or kaha .....
4/6/24, 14:43 - Pawan: Ha ha agar tum middle class vale to hm kaha he honge
4/6/24, 14:43 - Himani BTech : <Media omitted>
4/6/24, 14:44 - Himani BTech : Tum to zudio Jake red velvet khane vale log ho 😏
4/6/24, 14:44 - Gaurav Joshi: Diksha ji or himani ji hue yrr amir
4/6/24, 14:44 - Kiran: <Media omitted>
4/6/24, 14:44 - Himani BTech : <Media omitted>
4/6/24, 14:44 - Gaurav Joshi: Beta ab toh bhul krr nhi augha mai
4/6/24, 14:44 - Kiran: Kbbbb
4/6/24, 14:45 - Himani BTech : Tomorrow
4/6/24, 14:46 - Pawan: Tomorrow never come
4/6/24, 14:46 - Pawan: Aaj he chalo
4/6/24, 14:46 - Himani BTech : Vah beta
4/6/24, 14:46 - Himani BTech : Khuch bhi
4/6/24, 14:46 - Himani BTech : Ya log kal na aya..aj to bhul jao
4/6/24, 15:08 - Nirjala: Kab aur kon kon jara
4/6/24, 15:52 - Himani BTech : Yr sorry u are late
4/6/24, 15:52 - Himani BTech : Ab to sab na cancel kar diya
4/6/24, 15:58 - Ritesh: Mai bhi arah hu
4/6/24, 15:58 - Ritesh: But mere pe paisa nahi hai
4/6/24, 15:58 - Pawan: Ha ha chal
4/6/24, 15:58 - Ritesh: 10 10 ruppe jodh do sab mere liyee
4/6/24, 15:59 - Ritesh: Chal mai game khelra hu
4/6/24, 15:59 - Himani BTech : <Media omitted>
4/6/24, 15:59 - Pawan: Mummy ne bhej re to pase ka bahana bana leta hu 🤫🤫
4/6/24, 16:02 - Nirjala: Yeh tho jyada ho gaya 🤣🤣
4/6/24, 16:04 - Himani BTech : Abe kitna bariya Idea hai ba
4/6/24, 16:05 - Nirjala: Hnn vese bhura bhi nahi hai 🤣
4/6/24, 16:05 - Pawan: Vahe 1 no h
4/6/24, 16:05 - Himani BTech : Ya deko 🤣🤣🤣
4/6/24, 17:11 - Ritesh: Jana hai nahi jana jaldi batao
4/6/24, 17:11 - Ritesh: Kon kon arah hai
4/6/24, 17:11 - Ritesh: Piyush gym chalra?
4/6/24, 17:11 - Piyush Ñegi: Yess
4/6/24, 17:11 - Piyush Ñegi: Of course
4/6/24, 17:11 - Ritesh: Aja fir 5.30 pe nikalree
4/6/24, 17:12 - Piyush Ñegi: Abhi
4/6/24, 17:12 - Ritesh: Hn
4/6/24, 17:12 - Piyush Ñegi: Chal
4/6/24, 17:12 - Piyush Ñegi: Pawan
4/6/24, 17:12 - Ritesh: 5.30 pee anaa
4/6/24, 17:12 - Ritesh: Call nahi uthara
4/6/24, 17:12 - Piyush Ñegi: Ruk
4/7/24, 14:19 - Himani BTech :
4/7/24, 14:17 - Himani BTech : Oya kha ho ba
4/7/24, 14:42 - Kiran: M bol ni skti bhyii
4/7/24, 14:42 - Kiran: Sb soye h😂
4/7/24, 17:50 - Kiran:
4/8/24, 10:29 - Himani BTech : Hlo guys
4/8/24, 10:29 - Himani BTech : I go nainital
4/8/24, 10:29 - Himani BTech : Anybody coming
4/8/24, 10:33 - Pawan: Abe subeh qq nahe bola
4/8/24, 10:33 - Pawan: Aab time ho gaya hai
4/8/24, 10:35 - Nirjala: Continue your planing 🤣🤣
4/8/24, 10:36 - Nirjala: Jaldi yaad aa gyi
4/8/24, 10:41 - Himani BTech : Are 😂

In [19]:
print(type(data))

<class 'str'>

In [20]:
pattern = '\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [21]:
messages = re.split(pattern, data)[1:]
messages

['Pawan: \n',
 'Diksha Joshi: Guys m apne new ghr m gye hu\n',
 'Diksha Joshi: 😂😂😂\n',
 'Diksha Joshi: To ma kuch bole ni pa re\n',
 'Diksha Joshi: Wrna m bhut bolne k mne h\n',
 '(Chandan): Dishaaa\n',
 'Gaurav Joshi: <Media omitted>\n',
 'Gaurav Joshi: <Media omitted>\n',
 'Gaurav Joshi: <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Himani BTech : Oya parso ki photos bhejo\n',
 'Himani BTech : Royal vali\n',
 '(Chandan): This message was deleted\n',
 '(Chandan): This message was deleted\n',
 'Ritesh: Bhai sahab\n',
 'Ritesh: Sahi hai\n',
 'Kiran: Guys tum personally gye ho na to ye photoa bhi personally share kro☠️☠️\n',
 'Diksha Joshi: Ye chandu dadi se kaho\n',
 'Diksha Joshi: Ye grup to band tha ky hua phir😂😂\n',
 '(Chandan): ?\n',
 'Himani BTech : Owner na khol Diya vapas sa ...Pawan 😂😂\n',
 'Gaurav Joshi: Beta yai sahi hum kya gyai\n',
 'Gaurav Joshi: Screenshot mrai\n',
 'Himani BTech : Konsi language mai bol reha hai ba ... samajh ni ara\n',
 'Gaurav Joshi: Kux nhi chd ab language bhi smj nhi ayagi\n',
 'Himani BTech : Abe 🤣...ya kya bat hui\n',
 'Gaurav Joshi: Nothing else\n',
 'Himani BTech : Thik hogaya\n',
 'Gaurav Joshi: Hmm\n',
 'Gaurav Joshi: This message was deleted\n',
 '(Chandan): This message was deleted\n',
 'Himani BTech : Khuch bhi matlab...\n',
 'Himani BTech : Aj to bhut Bakkar lag reha hai mujhe\n',
 'Himani BTech : Roomate bhi ni ayi hai aur agar bagal bhi bhut Kam log hai\n',
 '(Chandan): This message was deleted\n',
 '(Chandan): Raat ghost na ayaae\n',
 'Himani BTech : Hogaya bhyi tu so ja... jayada ghost mat kar 😐😐\n',
 'Gaurav Joshi: Anshi kaha hai tere pram mitra\n',
 'Himani BTech : Apne room pa\n',
 'Himani BTech : Usna hair colour karvaya hai\n',
 'Gaurav Joshi: Oh\n',
 'Himani BTech : Yoo\n',
 'Gaurav Joshi: Ab toh or axi lg rahi hogi\n',
 'Himani BTech : Abe bhari 😂🤣\n',
 'Gaurav Joshi: Nhi yrr\n',
 'Himani BTech : Patani itna bakkawas colour ky karaya\n',
 '(Chandan): This message was deleted\n',
 'Gaurav Joshi: Asa mt bol\n',
 'Himani BTech : Pink type ka\n',
 '(Chandan): This message was deleted\n',
 'Gaurav Joshi: Abe tum log kya jano yai colour vegera\n',
 'Gaurav Joshi: Kitna axa lgta himani mere akho se dekh axa lgaiga😁\n',
 'Himani BTech : Abe caremal karati to ak no lagta\n',
 'Himani BTech : Ohhh\n',
 'Himani BTech : 🤣😂\n',
 'Gaurav Joshi: Yep\n',
 'Himani BTech : This message was deleted\n',
 'Gaurav Joshi: 😁😁\n',
 'Gaurav Joshi: Kux nhi krr rahe thai\n',
 'Himani BTech : Thik hogaya yr\n',
 'Himani BTech : Net bhi khatam ho gaya hai mera ...aur pg ka wifi bhi kharab ho gaya hai\n',
 'Gaurav Joshi: Sahi hai mai krr du recharge 😂\n',
 'Himani BTech : Na yr ...\n',
 'Himani BTech : I am an independent women\n',
 'Gaurav Joshi: Chl\n',
 'Gaurav Joshi: Be\n',
 'Himani BTech : Bhale hi Ghar valo ka samne bheek mangi\n',
 '(Chandan): Bol mat karde recharge\n',
 'Himani BTech : Parde 😂😂😂😂\n',
 'Gaurav Joshi: Independent women hai toh pocket money lena bnd krr de\n',
 'Himani BTech : Puri bat to sun 😂😂\n',
 'Himani BTech : Abe pura padhe\n',
 "Gaurav Joshi: Oh that's a point\n",
 'Himani BTech : Yesss\n',
 "Himani BTech : Don't give sudden reactions\n",
 'Gaurav Joshi: On the spot krta hu mai\n',
 'Gaurav Joshi: Mag ka intezar nhi sidha reply\n',
 'Himani BTech : Na na itna spontaneous ni hona chahiye\n',
 'Himani BTech : Tabhi to ladki ni pat ri hai\n',
 'Gaurav Joshi: Ab tumhari trah processor slow nhi hai\n',
 'Gaurav Joshi: Msg*\n',
 'Himani BTech : Ha ha ku ni 😂\n',
 'Pawan: Ooe ye anshi hai kon\n',
 'Gaurav Joshi: Mere crush\n',
 'Gaurav Joshi: 😁\n',
 'Himani BTech : Abhi last mai tujhe ak lardki dekhai thi video call pa...vahi\n',
 'Pawan: Kab\n',
 'Pawan: Mane ne deekha\n',
 'Himani BTech : Bhut bardiya\n',
 'Gaurav Joshi: Abe himani photo bhej de yrr\n',
 'Himani BTech : Pagal hai kya\n',
 'Gaurav Joshi: Wallpaper mai lagaunga\n',
 'Gaurav Joshi: Apni or anshi ki\n',
 'Gaurav Joshi: Bdd mai crop krkai tujhai hta dugha\n',
 'Himani BTech : Ha beta yhi karega aur kar bhi kya Sakta hai\n',
 'Gaurav Joshi: Hn phr\n',
 'Gaurav Joshi: \n',
 'Gaurav Joshi: 😂😁\n',
 'Himani BTech : Ha re bhej di usa Maine 😂\n',
 'Himani BTech : \n',
 'Diksha Joshi: This message was deleted\n',
 'Diksha Joshi: This message was deleted\n',
 'Gaurav Joshi: Sahi hi Kiya\n',
 'Gaurav Joshi: \n',
 'Kiran: Ye duplicate nora fatehi kyu lgra😂🤡\n',
 'Gaurav Joshi: Beta class ka don hai vo teacher bhi drtai hai\n',
 'Gaurav Joshi: Issay\n',
 'Ritesh: 💀💀💀💀💀\n',
 'Ritesh: Bro\n',
 'Ritesh: 🌚\n',
 'Kiran: Vdeo dekh ke to ni lgra👽☠️\n',
 'Diksha Joshi: 🥺😏\n',
 'Gaurav Joshi: Look mai mtt\n',
 'Kiran: Kon jaara\n',
 'Kiran: M jaanti hu\n',
 'Gaurav Joshi: 😁😁😁\n',
 'Kiran: Mera hi padosi h😂\n',
 'Gaurav Joshi: Oh axa\n',
 'Pawan: Abe\n',
 'Ritesh: Guys c mai paheli 2 unit he arahi hogi naa?\n',
 'Ritesh: Ya class bhi arah hai?\n',
 'Gaurav Joshi: 2.5\n',
 'Ritesh: Guys\n',
 'Ritesh: OS ke notes bhejdoo yaar\n',
 'Ritesh: Pdf\n',
 'Ritesh: Unit 1 and 2\n',
 'Diksha Joshi: Kse bhej dk😂😂\n',
 'Diksha Joshi: Banaye jo nii\n',
 'Ritesh: Areey kuch bhi bhej doo padunga kaha se\n',
 'Pawan: This message was deleted\n',
 'Pawan: <Media omitted>\n',
 'Ritesh: Syllabus to bhej doo\n',
 'Gaurav Joshi: Computer system organisation\n computer system architecture \noperating system structure\n operating system operations\n basic of process management\n storage management \nprotection and security\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 '(Chandan): <Media omitted>\n',
 'Gaurav Joshi: Threading\n multi core programming\n multi threading models\n thread library\n implicit esplicit \nor threading problems\n process concept \nprocess scheduling \n operations on process\n Inter process communication\n or IPCS system\n',
 'Ritesh: Baas\n',
 'Ritesh: Fk\n',
 'Gaurav Joshi: H\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Ritesh: Toinks\n',
 'Ritesh: Joo Banda uss teacher ki notes bana saktaa hai woo kuch bhi kaar saktaa hai life mai\n',
 'Diksha Joshi: WAP of system call and define ?\nWhat is the Operating system and explain its types?\nDifference between multi-tasking and multi-programing?\nElaborate management process? \nExplain multi-threading? \nProcess of management?\n',
 'Diksha Joshi: Define the Threading problem and how can you fix those?\nDescribe thread libraries?\nWhat is process scheduling?\nHow many types of operation are performed in processes explaining each one?\nWhat are the examples of IPC system?\n',
 'Diksha Joshi: Explain types of system call?\nWhat are system call?\n',
 'Diksha Joshi: Baki introduction to OS theory hai vo tum apne mn se likh sak tha ho\n',
 'Diksha Joshi: Ye imp haa\n',
 'Ritesh: This message was deleted\n',
 'Himani BTech : Hlo BCA band ....b.tech band is back\n',
 'Pawan: Hll\n',
 'Piyush Ñegi: Hello\n',
 'Himani BTech : Oh bhyi bhyi salu bhai\n',
 'Himani BTech : First time Time reply\n',
 'Himani BTech : Hiii\n',
 'Pawan: Programming se fursat mil gae hai bal\n',
 'Himani BTech : Vahi vahi 😂\n',
 'Piyush Ñegi: Mil gaye\n',
 'Pawan: Sale phone to utha\n',
 'Pawan: Ka gf\n',
 'Himani BTech : Thik hogaya phir kal nainital chal re ho ghumne sab\n',
 'Piyush Ñegi: Window he corrupt ho gaye\n',
 'Himani BTech : Abe 🤣😂\n',
 'Piyush Ñegi: \U0001f979\U0001f979\U0001f979\U0001f979\U0001f979\n',
 'Ritesh: Abe piyush\n',
 'Ritesh: Tu baat bhi karta hai\n',
 'Piyush Ñegi: Haa\n',
 'Ritesh: <Media omitted>\n',
 'Piyush Ñegi: Or tu bhe kar\n',
 'Piyush Ñegi: ☠️☠️☠️☠️\n',
 'Ritesh: Pakka pawan. Hai\n',
 'Piyush Ñegi: Abe\n',
 'Ritesh: Ye🤣\n',
 'Piyush Ñegi: Nahi ha\n',
 'Piyush Ñegi: You deleted this message\n',
 'Piyush Ñegi: You deleted this message\n',
 'Ritesh: 5.30\n',
 'Piyush Ñegi: Okk\n',
 'Himani BTech : Oya u people are supposed to answer this okay\n',
 'Piyush Ñegi: Noo\n',
 'Pawan: <Media omitted>\n',
 'Piyush Ñegi: Jhut bol raha ha\n',
 'Himani BTech : Thik hogaya matlab salu bhai is ready\n',
 'Pawan: <Media omitted>\n',
 'Piyush Ñegi: Naa\n',
 'Piyush Ñegi: Just joking\n',
 'Himani BTech : Salu bhai pitne vale hai aur khuch ni\n',
 'Piyush Ñegi: kisse\n',
 'Himani BTech : Ofcourse mujhse 🤣\n',
 'Piyush Ñegi: Maf kar do dede\n',
 'Piyush Ñegi: \U0001f979\U0001f979\U0001f979\U0001f979\n',
 'Himani BTech : Are are salu bhai ap mafi na mange 🤣\n',
 'Piyush Ñegi: 😂😂😂\n',
 'Piyush Ñegi: Pawan kha gaya\n',
 'Himani BTech : So gaya vo ab\n',
 'Piyush Ñegi: Accha\n',
 'Pawan: Kuch b\n',
 'Piyush Ñegi: Vahi to\n',
 'Piyush Ñegi: Jhuti\n',
 'Pawan: <Media omitted>\n',
 'Piyush Ñegi: Sahi pakde Hai\n',
 'Diksha Joshi: Piyush ke dady se batte\n',
 'Diksha Joshi: Hue\n',
 'Diksha Joshi: Meri aaj\n',
 'Diksha Joshi: 😂😂\n',
 'Diksha Joshi: Hai na piyush\n',
 'Himani BTech : Oya diksha is back\n',
 'Piyush Ñegi: Yess\n',
 'Diksha Joshi: Diksha is going \nM sleeping\n',
 'Piyush Ñegi: Side ma baitha hua tha\n',
 'Diksha Joshi: Piyush send address m aare kl😂😂\n',
 'Diksha Joshi: Ha hash ra tha\n',
 'Diksha Joshi: 😂😂\n',
 'Himani BTech : Oya bata ba kal nainital chalegi\n',
 'Diksha Joshi: Brooo \nMera pper pass h\n',
 'Diksha Joshi: Abhi khi ni ghumnr\n',
 'Diksha Joshi: 1 month baad contact plz\n',
 'Himani BTech : Thik hogaya yr diksha thik hai\n',
 'Diksha Joshi: Hihii😂😂\n',
 'Himani BTech : Aj to hogaya 😏😏😏😏\n',
 'Diksha Joshi: Ky ho gyaa\n',
 'Diksha Joshi: Abe koi aur ni hora ky\n',
 'Diksha Joshi: Tyyar\n',
 'Himani BTech : Yahi dosti yahi pyar... abhinav style mai 🤣🤣🤣\n',
 'Diksha Joshi: Chandu bhai to Hanuman dham gye h aj dp m dekhra \nHai na dadi\n',
 'Piyush Ñegi: Chandan se puch o\n',
 'Diksha Joshi: Ap abhinav ne hai na\n',
 'Diksha Joshi: 😂\n',
 'Diksha Joshi: Sallu bhai ppa ne bola ky ki aj whatsapp pr on rhna\n',
 'Himani BTech : Vahi vahi\n',
 'Diksha Joshi: Hihihi\n',
 'Himani BTech : I also wanted the same answer\n',
 'Diksha Joshi: Ya ap Pawan ke ghr gye ha\nAur uske hath h keyboard m\n',
 'Diksha Joshi: For what question\n',
 'Piyush Ñegi: Yes\n',
 'Piyush Ñegi: Pawan he ha\n',
 'Diksha Joshi: Dekha😂😂\n',
 'Piyush Ñegi: Sahi pakde hai\n',
 'Diksha Joshi: Ham to Nash nash se rubaru ha\n',
 'Himani BTech : How salu bhai is typing\n',
 'Diksha Joshi: Cauze he is replaced by\n',
 'Himani BTech : Oh bhyi 😂\n',
 'Diksha Joshi: Mr Pawan bhandari\n',
 'Diksha Joshi: 😂\n',
 'Himani BTech : Pawan dadi kaha 🤣🤣\n',
 'Diksha Joshi: Ha ye ye\n',
 'Piyush Ñegi: Chandan bhe kaha ha\n',
 'Piyush Ñegi: Yad aati ha\n',
 "Himani BTech : Bakki sab ki to na hogyi Jane ka liya to nirjala ma'am kya kehna chahinge\n",
 'Diksha Joshi: Are chandu gaurav bchr h\n',
 'Diksha Joshi: Avii\n',
 'Diksha Joshi: Apko sbke sahmati sune chahiye\n',
 'Himani BTech : Gaurav mana kar reha haj hai\n',
 'Piyush Ñegi: Kon kon ha trip ma\n',
 'Himani BTech : Jo ana chahe\n',
 'Piyush Ñegi: Name plezz\n',
 'Himani BTech : Ap kisko bulna chahte hai\n',
 'Piyush Ñegi: Hamara hai hi Kaun\n',
 'Diksha Joshi: Kb kra\n',
 'Diksha Joshi: Kiraan😂😂\n',
 'Himani BTech : Are Kiran bhi to hai 🤣🤣🤣🤣\n',
 'Himani BTech : Usa to bhul hi gayi thi 🤣🤣\n',
 'Piyush Ñegi: What\n',
 'Pawan: Sahe bola\n',
 "Himani BTech : Agla Sunday ko birthday hai ma'am ka\n",
 'Pawan: Kiran programing b sikha dege\n',
 'Diksha Joshi: Are ha m to bhul hi gye😂😂😂\n',
 'Himani BTech : Are diksha personal chats u know\n',
 'Himani BTech : Abe 🤣\n',
 'Himani BTech : Sir bol re hai ki gadi ni hai ...kisma aunga\n',
 'Piyush Ñegi: Jalve Hain Himani ji ke\n',
 'Himani BTech : Are salu bhai aj itna kesa bolre hai ... mujhe khuch samajh ni ara\n',
 'Himani BTech : 🧐\n',
 'Himani BTech : Dal mai khuch to kala hai 😂\n',
 'Piyush Ñegi: 😂😂😂😂😂\n',
 'Piyush Ñegi: Puri dal hi Kali hai\n',
 'Pawan: Daal pure he kale h\n',
 'Diksha Joshi: Aare😂😂\n',
 'Himani BTech : Na na ab yakeen ho gaya ki pawan aur salu bhai alag alag jah hai\n',
 'Diksha Joshi: Na too ik hi jgh h\n',
 'Pawan: Kya\n',
 'Diksha Joshi: Ik hath m apna phn ik m saalu dadi ka\n',
 'Himani BTech : Choti moti buses mai ni ate na sir isliye\n',
 'Himani BTech : Na na\n',
 'Piyush Ñegi: Haa\n',
 'Pawan: <Media omitted>\n',
 'Diksha Joshi: Aare uneh chahiye royal ik dum\n',
 'Diksha Joshi: Ha ye piyush ka ghr ma\n',
 'Pawan: Ye kahe se kahe tak lag raha hi salu bhi ka ghr\n',
 'Piyush Ñegi: Me Ghar ke photo ha\n',
 'Diksha Joshi: Kyuki Pawan ke room m\n',
 'Himani BTech : Agar asa hota to dono mai alag alag likhta\n',
 'Diksha Joshi: Ye design ni\n',
 'Diksha Joshi: Ha\n',
 'Diksha Joshi: Plane h😂😂😂😂\n',
 'Himani BTech : Abe ni ba pawan new house mai shift ho gaya hai\n',
 'Diksha Joshi: Are kab 😂😂\n',
 'Himani BTech : Samjhe diksha\n',
 'Himani BTech : Kab ke\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : Vahi to\n',
 'Himani BTech : Ha re samajh gaya\n',
 'Pawan: <Media omitted>\n',
 'Gaurav Joshi: Abe yrr yai royal voyal kux nhi hn\n',
 'Gaurav Joshi: Yahai se pehle bhimtal bus mai or phr nanital kitna lamba rsta hai\n',
 'Himani BTech : <Media omitted>\n',
 'Himani BTech : Abe tum direct nainital jaoge pagal\n',
 'Himani BTech : Tum ku aoge bhimtal\n',
 'Gaurav Joshi: Ab logo ko royal lg raha toh kya hi krr skta hu standard hi kux asa mera\n',
 'Himani BTech : Chal chal hogaya😏😏😏\n',
 'Pawan: <Media omitted>\n',
 'Gaurav Joshi: Abe maine toh nhi bola jisne bola unse puxo\n',
 'Pawan: <Media omitted>\n',
 'Gaurav Joshi: Abe yai\n',
 'Himani BTech : <Media omitted>\n',
 'Gaurav Joshi: Suruvt kisnai ki bhai yai toh dekhna\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : Mai to thi na ...lakin 😏😏😏\n',
 'Pawan: <Media omitted>\n',
 'Gaurav Joshi: Bhai yrr asa kux nhi hai yrr kaha me lower middle class vala ldka or kaha .....\n',
 'Pawan: Ha ha agar tum middle class vale to hm kaha he honge\n',
 'Himani BTech : <Media omitted>\n',
 'Himani BTech : Tum to zudio Jake red velvet khane vale log ho 😏\n',
 'Gaurav Joshi: Diksha ji or himani ji hue yrr amir\n',
 'Kiran: <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Gaurav Joshi: Beta ab toh bhul krr nhi augha mai\n',
 'Kiran: Kbbbb\n',
 'Himani BTech : Tomorrow\n',
 'Pawan: Tomorrow never come\n',
 'Pawan: Aaj he chalo\n',
 'Himani BTech : Vah beta\n',
 'Himani BTech : Khuch bhi\n',
 'Himani BTech : Ya log kal na aya..aj to bhul jao\n',
 'Nirjala: Kab aur kon kon jara\n',
 'Himani BTech : Yr sorry u are late\n',
 'Himani BTech : Ab to sab na cancel kar diya\n',
 'Ritesh: Mai bhi arah hu\n',
 'Ritesh: But mere pe paisa nahi hai\n',
 'Pawan: Ha ha chal\n',
 'Ritesh: 10 10 ruppe jodh do sab mere liyee\n',
 'Ritesh: Chal mai game khelra hu\n',
 'Himani BTech : <Media omitted>\n',
 'Pawan: Mummy ne bhej re to pase ka bahana bana leta hu 🤫🤫\n',
 'Nirjala: Yeh tho jyada ho gaya 🤣🤣\n',
 'Himani BTech : Abe kitna bariya Idea hai ba\n',
 'Nirjala: Hnn vese bhura bhi nahi hai 🤣\n',
 'Pawan: Vahe 1 no h\n',
 'Himani BTech : Ya deko 🤣🤣🤣\n',
 'Ritesh: Jana hai nahi jana jaldi batao\n',
 'Ritesh: Kon kon arah hai\n',
 'Ritesh: Piyush gym chalra?\n',
 'Piyush Ñegi: Yess\n',
 'Piyush Ñegi: Of course\n',
 'Ritesh: Aja fir 5.30 pe nikalree\n',
 'Piyush Ñegi: Abhi\n',
 'Ritesh: Hn\n',
 'Piyush Ñegi: Chal\n',
 'Piyush Ñegi: Pawan\n',
 'Ritesh: 5.30 pee anaa\n',
 'Ritesh: Call nahi uthara\n',
 'Piyush Ñegi: Ruk\n',
 'Himani BTech : \n',
 'Himani BTech : Oya kha ho ba\n',
 'Kiran: M bol ni skti bhyii\n',
 'Kiran: Sb soye h😂\n',
 'Kiran: \n',
 'Himani BTech : Hlo guys\n',
 'Himani BTech : I go nainital\n',
 'Himani BTech : Anybody coming\n',
 'Pawan: Abe subeh qq nahe bola\n',
 'Pawan: Aab time ho gaya hai\n',
 'Nirjala: Continue your planing 🤣🤣\n',
 'Nirjala: Jaldi yaad aa gyi\n',
 'Himani BTech : Are 😂\n',
 'Himani BTech : I going then\n',
 'Nirjala: <Media omitted>\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Himani BTech : 🤣🤣🤣\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : Abe 🤣😂\n',
 'Kiran: <Media omitted>\n',
 'Kiran: <Media omitted>\n',
 'Himani BTech : Abe 🤣\n',
 'Gaurav Joshi: Hai kn yai\n',
 'Himani BTech : Hairstyle\n',
 'Himani BTech : 🤣🤣\n',
 'Gaurav Joshi: Oh mujhe lga ki koi social media influencer hai\n',
 'Ritesh: Kuch time mai mere baal bhi Aisa he hone wale hai\n',
 'Himani BTech : \n',
 'Pawan: \n',
 'Pawan: <Media omitted>\n',
 'Pawan: <Media omitted>\n',
 'Ritesh: Himani kuch nahi bolraa baas jo tere sang ladkiyaan thi woo bata dee\n',
 'Ritesh: @\u2068Himani BTech \u2069\n',
 'Ritesh: Pic bhejnaa plezz\n',
 'Ritesh: Himani jaan lele but emoji react karke ignore na kaar\n',
 'Himani BTech : Are 😂\n',
 'Himani BTech : Abe kitne chahiye tujhe bhyi\n',
 'Himani BTech : Already 3 hai\n',
 'Ritesh: Kyaa\n',
 'Himani BTech : Yess🤣\n',
 'Ritesh: Himani mai nahi janata pic bhejdee plezz\n',
 'Ritesh: Muje sans nahi arahi\n',
 'Himani BTech : Abe abe 🤣😂\n',
 'Himani BTech : Ruk personally bhej ri hu\n',
 'Kiran: This message was deleted\n',
 'Himani BTech : Kya photo bhej ri hai ba\n',
 'Ritesh: Udtaa he firruu in hawaoo mai kahi\n',
 'Ritesh: Chasme wali\n',
 'Ritesh: \U0001f979\U0001f979\U0001f979\n',
 'Pawan: M b vahe keh raha tha\n',
 'Ritesh: duur rah\n',
 'Ritesh: Dikh maat jaiyoo\n',
 'Himani BTech : <Media omitted>\n',
 'Ritesh: Himani bio data plezz\n',
 'Himani BTech : Abe 🤣\n',
 'Ritesh: age name school\n',
 'Ritesh: muje sab janna hai\n',
 'Himani BTech : Are sorry hogayi\n',
 'Himani BTech : Vo to ni ho payega\n',
 'Ritesh: Chal fir bye haan\n',
 'Himani BTech : Yess\n',
 'Ritesh: Aaj ye baat ho gayi\n',
 'Himani BTech : Are 😂\n',
 'Ritesh: Jese mai koi serial killer hungaa\n',
 'Himani BTech : BBA vali hai\n',
 'Ritesh: Tab rahne de\n',
 'Ritesh: Unmai dimag kaam hota\n',
 'Himani BTech : <Media omitted>\n',
 'Ritesh: 💪🗿\n',
 'Pawan: Ab bole na baat\n',
 'Pawan: Yahe baat Maine b bole the\n',
 'Himani BTech : Abe terko full detail di to thi\n',
 'Himani BTech : Video call pa\n',
 'Pawan: <Media omitted>\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Gaurav Joshi: Merko chlegi\n',
 'Gaurav Joshi: 😂\n',
 'Himani BTech : <Media omitted>\n',
 'Pawan: This message was deleted\n',
 'Pawan: <Media omitted>\n',
 'Gaurav Joshi: Hum single logo ka drd nhi smj skti himani\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Kiran: ☠️\n',
 'Gaurav Joshi: Mere bnava de himani bakiyo ko chd de\n',
 'Pawan: <Media omitted>\n',
 'Himani BTech : <Media omitted>\n',
 'Gaurav Joshi: Abe mere bndi ho toh mai ghumne bhi jau\n',
 'Gaurav Joshi: Yr\n',
 'Himani BTech : <Media omitted>\n',
 'Gaurav Joshi: Mere setting krva hai phr toh bunk krkai Nanital haldwani basani hr jgah gumnai jaugha\n',
 'Himani BTech : Nikal la tu 😏😏😏😏\n',
 'Gaurav Joshi: 😂😂😂\n',
 'Gaurav Joshi: Mtlb apna mai cencel smjhu 😂\n',
 'Himani BTech : Ha beta bilkul 😏😏\n',
 'Gaurav Joshi: Himani yrr group ek tere bhabhi add ho kitna axa lgegha\n',
 'Himani BTech : 😏😏😏😏😏\n',
 'Gaurav Joshi: Krva de mere setting group kai ek member or add ho jyagha\n',
 'Himani BTech : 😏😏😏😏😏\n',
 'Gaurav Joshi: Kux bol bhi le 😂\n',
 'Himani BTech : Nikal le 😏😏😏😏😏\n',
 'Gaurav Joshi: Hahah\n',
 'Gaurav Joshi: Then bye\n',
 'Himani BTech : Byeee 🙃🙃🙃🙃\n',
 'Pawan: \n',
 'Pawan: \n',
 'Himani BTech : \n',
 'Gaurav Joshi: <Media omitted>\n',
 'Gaurav Joshi: 😁\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Piyush Ñegi: <Media omitted>\n',
 'Pawan: \n',
 '(Chandan): <Media omitted>\n',
 'Diksha Joshi: Congratulations chandu bhai \nAb partyy😂😂❤️\n',
 'Gaurav Joshi: Happiest birthday kiran mam ko\n',
 'Kiran: Thank you 😇\n',
 'Piyush Ñegi: Happy birthday Kiran ji\n',
 'Kiran: Thankyou jii\n',

In [22]:
dates = re.findall(pattern, data)
dates

['3/30/24, 18:16 - ',
 '3/30/24, 18:18 - ',
 '3/30/24, 18:18 - ',
 '3/30/24, 18:18 - ',
 '3/30/24, 18:18 - ',
 '3/30/24, 18:19 - ',
 '3/30/24, 18:24 - ',
 '3/30/24, 18:24 - ',
 '3/30/24, 18:25 - ',
 '3/30/24, 19:40 - ',
 '3/30/24, 19:40 - ',
 '3/30/24, 19:41 - ',
 '3/30/24, 19:41 - ',
 '3/30/24, 19:48 - ',
 '3/30/24, 19:48 - ',
 '3/30/24, 19:49 - ',
 '3/30/24, 19:49 - ',
 '3/30/24, 19:54 - ',
 '3/30/24, 19:54 - ',
 '3/30/24, 19:54 - ',
 '3/30/24, 19:55 - ',
 '3/30/24, 20:04 - ',
 '3/30/24, 20:33 - ',
 '3/30/24, 20:33 - ',
 '3/30/24, 20:34 - ',
 '3/30/24, 20:35 - ',
 '3/30/24, 20:37 - ',
 '3/30/24, 20:37 - ',
 '3/30/24, 20:37 - ',
 '3/30/24, 20:45 - ',
 '3/30/24, 20:50 - ',
 '3/30/24, 20:58 - ',
 '3/30/24, 20:58 - ',
 '3/30/24, 20:59 - ',
 '3/30/24, 20:59 - ',
 '3/30/24, 20:59 - ',
 '3/30/24, 21:00 - ',
 '3/30/24, 21:00 - ',
 '3/30/24, 21:02 - ',
 '3/30/24, 21:02 - ',
 '3/30/24, 21:03 - ',
 '3/30/24, 21:03 - ',
 '3/30/24, 21:03 - ',
 '3/30/24, 21:03 - ',
 '3/30/24, 21:03 - ',
 '3/30/24, 21:03 - ',
 '3/30/24, 21:03 - ',
 '3/30/24, 21:04 - ',
 '3/30/24, 21:04 - ',
 '3/30/24, 21:04 - ',
 '3/30/24, 21:04 - ',
 '3/30/24, 21:04 - ',
 '3/30/24, 21:04 - ',
 '3/30/24, 21:04 - ',
 '3/30/24, 21:05 - ',
 '3/30/24, 21:05 - ',
 '3/30/24, 21:05 - ',
 '3/30/24, 21:05 - ',
 '3/30/24, 21:06 - ',
 '3/30/24, 21:06 - ',
 '3/30/24, 21:06 - ',
 '3/30/24, 21:07 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:08 - ',
 '3/30/24, 21:09 - ',
 '3/30/24, 21:09 - ',
 '3/30/24, 21:09 - ',
 '3/30/24, 21:09 - ',
 '3/30/24, 21:09 - ',
 '3/30/24, 21:09 - ',
 '3/30/24, 21:10 - ',
 '3/30/24, 21:10 - ',
 '3/30/24, 21:10 - ',
 '3/30/24, 21:11 - ',
 '3/30/24, 21:11 - ',
 '3/30/24, 21:11 - ',
 '3/30/24, 21:11 - ',
 '3/30/24, 21:12 - ',
 '3/30/24, 21:12 - ',
 '3/30/24, 21:12 - ',
 '3/30/24, 21:13 - ',
 '3/30/24, 21:13 - ',
 '3/30/24, 21:13 - ',
 '3/30/24, 21:13 - ',
 '3/30/24, 21:13 - ',
 '3/30/24, 21:13 - ',
 '3/30/24, 21:13 - ',
 '3/30/24, 21:14 - ',
 '3/30/24, 21:14 - ',
 '3/30/24, 21:15 - ',
 '3/30/24, 21:15 - ',
 '3/30/24, 21:16 - ',
 '3/30/24, 21:16 - ',
 '3/30/24, 21:17 - ',
 '3/30/24, 21:18 - ',
 '3/30/24, 21:23 - ',
 '3/30/24, 21:23 - ',
 '3/30/24, 21:25 - ',
 '3/30/24, 21:26 - ',
 '3/30/24, 21:27 - ',
 '3/30/24, 21:28 - ',
 '3/30/24, 21:28 - ',
 '3/30/24, 21:28 - ',
 '3/30/24, 21:28 - ',
 '3/30/24, 21:29 - ',
 '3/30/24, 21:29 - ',
 '3/30/24, 21:29 - ',
 '3/30/24, 21:29 - ',
 '3/30/24, 21:29 - ',
 '3/30/24, 21:29 - ',
 '3/30/24, 21:29 - ',
 '3/30/24, 21:30 - ',
 '3/30/24, 21:31 - ',
 '3/30/24, 21:59 - ',
 '4/2/24, 06:38 - ',
 '4/2/24, 06:38 - ',
 '4/2/24, 07:03 - ',
 '4/2/24, 19:17 - ',
 '4/2/24, 19:17 - ',
 '4/2/24, 19:17 - ',
 '4/2/24, 19:17 - ',
 '4/2/24, 19:19 - ',
 '4/2/24, 19:19 - ',
 '4/2/24, 19:20 - ',
 '4/2/24, 19:25 - ',
 '4/2/24, 19:26 - ',
 '4/2/24, 19:32 - ',
 '4/2/24, 19:42 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:43 - ',
 '4/2/24, 19:44 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:47 - ',
 '4/2/24, 19:50 - ',
 '4/2/24, 19:50 - ',
 '4/2/24, 21:40 - ',
 '4/2/24, 21:40 - ',
 '4/2/24, 21:40 - ',
 '4/2/24, 21:40 - ',
 '4/2/24, 21:40 - ',
 '4/3/24, 08:13 - ',
 '4/6/24, 14:01 - ',
 '4/6/24, 14:02 - ',
 '4/6/24, 14:02 - ',
 '4/6/24, 14:02 - ',
 '4/6/24, 14:02 - ',
 '4/6/24, 14:03 - ',
 '4/6/24, 14:03 - ',
 '4/6/24, 14:03 - ',
 '4/6/24, 14:03 - ',
 '4/6/24, 14:03 - ',
 '4/6/24, 14:03 - ',
 '4/6/24, 14:04 - ',
 '4/6/24, 14:04 - ',
 '4/6/24, 14:04 - ',
 '4/6/24, 14:08 - ',
 '4/6/24, 14:10 - ',
 '4/6/24, 14:10 - ',
 '4/6/24, 14:10 - ',
 '4/6/24, 14:10 - ',
 '4/6/24, 14:10 - ',
 '4/6/24, 14:11 - ',
 '4/6/24, 14:11 - ',
 '4/6/24, 14:11 - ',
 '4/6/24, 14:11 - ',
 '4/6/24, 14:11 - ',
 '4/6/24, 14:11 - ',
 '4/6/24, 14:12 - ',
 '4/6/24, 14:12 - ',
 '4/6/24, 14:12 - ',
 '4/6/24, 14:14 - ',
 '4/6/24, 14:15 - ',
 '4/6/24, 14:15 - ',
 '4/6/24, 14:15 - ',
 '4/6/24, 14:15 - ',
 '4/6/24, 14:15 - ',
 '4/6/24, 14:16 - ',
 '4/6/24, 14:16 - ',
 '4/6/24, 14:16 - ',
 '4/6/24, 14:17 - ',
 '4/6/24, 14:17 - ',
 '4/6/24, 14:17 - ',
 '4/6/24, 14:17 - ',
 '4/6/24, 14:18 - ',
 '4/6/24, 14:18 - ',
 '4/6/24, 14:19 - ',
 '4/6/24, 14:19 - ',
 '4/6/24, 14:19 - ',
 '4/6/24, 14:19 - ',
 '4/6/24, 14:20 - ',
 '4/6/24, 14:20 - ',
 '4/6/24, 14:20 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:21 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:22 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:23 - ',
 '4/6/24, 14:24 - ',
 '4/6/24, 14:24 - ',
 '4/6/24, 14:24 - ',
 '4/6/24, 14:24 - ',
 '4/6/24, 14:24 - ',
 '4/6/24, 14:24 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:25 - ',
 '4/6/24, 14:26 - ',
 '4/6/24, 14:27 - ',
 '4/6/24, 14:29 - ',
 '4/6/24, 14:29 - ',
 '4/6/24, 14:29 - ',
 '4/6/24, 14:29 - ',
 '4/6/24, 14:30 - ',
 '4/6/24, 14:30 - ',
 '4/6/24, 14:30 - ',
 '4/6/24, 14:30 - ',
 '4/6/24, 14:30 - ',
 '4/6/24, 14:31 - ',
 '4/6/24, 14:31 - ',
 '4/6/24, 14:31 - ',
 '4/6/24, 14:31 - ',
 '4/6/24, 14:32 - ',
 '4/6/24, 14:32 - ',
 '4/6/24, 14:32 - ',
 '4/6/24, 14:32 - ',
 '4/6/24, 14:32 - ',
 '4/6/24, 14:33 - ',
 '4/6/24, 14:33 - ',
 '4/6/24, 14:33 - ',
 '4/6/24, 14:34 - ',
 '4/6/24, 14:34 - ',
 '4/6/24, 14:34 - ',
 '4/6/24, 14:34 - ',
 '4/6/24, 14:34 - ',
 '4/6/24, 14:35 - ',
 '4/6/24, 14:35 - ',
 '4/6/24, 14:35 - ',
 '4/6/24, 14:35 - ',
 '4/6/24, 14:35 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:36 - ',
 '4/6/24, 14:37 - ',
 '4/6/24, 14:37 - ',
 '4/6/24, 14:37 - ',
 '4/6/24, 14:37 - ',
 '4/6/24, 14:37 - ',
 '4/6/24, 14:37 - ',
 '4/6/24, 14:37 - ',
 '4/6/24, 14:38 - ',
 '4/6/24, 14:38 - ',
 '4/6/24, 14:38 - ',
 '4/6/24, 14:39 - ',
 '4/6/24, 14:39 - ',
 '4/6/24, 14:39 - ',
 '4/6/24, 14:39 - ',
 '4/6/24, 14:40 - ',
 '4/6/24, 14:40 - ',
 '4/6/24, 14:40 - ',
 '4/6/24, 14:40 - ',
 '4/6/24, 14:41 - ',
 '4/6/24, 14:41 - ',
 '4/6/24, 14:41 - ',
 '4/6/24, 14:41 - ',
 '4/6/24, 14:41 - ',
 '4/6/24, 14:42 - ',
 '4/6/24, 14:42 - ',
 '4/6/24, 14:42 - ',
 '4/6/24, 14:42 - ',
 '4/6/24, 14:42 - ',
 '4/6/24, 14:43 - ',
 '4/6/24, 14:43 - ',
 '4/6/24, 14:44 - ',
 '4/6/24, 14:44 - ',
 '4/6/24, 14:44 - ',
 '4/6/24, 14:44 - ',
 '4/6/24, 14:44 - ',
 '4/6/24, 14:44 - ',
 '4/6/24, 14:45 - ',
 '4/6/24, 14:46 - ',
 '4/6/24, 14:46 - ',
 '4/6/24, 14:46 - ',
 '4/6/24, 14:46 - ',
 '4/6/24, 14:46 - ',
 '4/6/24, 15:08 - ',
 '4/6/24, 15:52 - ',
 '4/6/24, 15:52 - ',
 '4/6/24, 15:58 - ',
 '4/6/24, 15:58 - ',
 '4/6/24, 15:58 - ',
 '4/6/24, 15:58 - ',
 '4/6/24, 15:59 - ',
 '4/6/24, 15:59 - ',
 '4/6/24, 15:59 - ',
 '4/6/24, 16:02 - ',
 '4/6/24, 16:04 - ',
 '4/6/24, 16:05 - ',
 '4/6/24, 16:05 - ',
 '4/6/24, 16:05 - ',
 '4/6/24, 17:11 - ',
 '4/6/24, 17:11 - ',
 '4/6/24, 17:11 - ',
 '4/6/24, 17:11 - ',
 '4/6/24, 17:11 - ',
 '4/6/24, 17:11 - ',
 '4/6/24, 17:12 - ',
 '4/6/24, 17:12 - ',
 '4/6/24, 17:12 - ',
 '4/6/24, 17:12 - ',
 '4/6/24, 17:12 - ',
 '4/6/24, 17:12 - ',
 '4/6/24, 17:12 - ',
 '4/7/24, 14:19 - ',
 '4/7/24, 14:17 - ',
 '4/7/24, 14:42 - ',
 '4/7/24, 14:42 - ',
 '4/7/24, 17:50 - ',
 '4/8/24, 10:29 - ',
 '4/8/24, 10:29 - ',
 '4/8/24, 10:29 - ',
 '4/8/24, 10:33 - ',
 '4/8/24, 10:33 - ',
 '4/8/24, 10:35 - ',
 '4/8/24, 10:36 - ',
 '4/8/24, 10:41 - ',
 '4/8/24, 10:41 - ',
 '4/8/24, 10:43 - ',
 '4/8/24, 10:43 - ',
 '4/8/24, 11:19 - ',
 '4/8/24, 11:19 - ',
 '4/8/24, 11:19 - ',
 '4/8/24, 11:20 - ',
 '4/8/24, 11:20 - ',
 '4/8/24, 11:20 - ',
 '4/8/24, 11:21 - ',
 '4/8/24, 12:03 - ',
 '4/8/24, 12:18 - ',
 '4/8/24, 12:18 - ',
 '4/8/24, 12:19 - ',
 '4/8/24, 14:21 - ',
 '4/8/24, 17:58 - ',
 '4/8/24, 18:42 - ',
 '4/8/24, 19:00 - ',
 '4/8/24, 19:03 - ',
 '4/8/24, 20:57 - ',
 '4/8/24, 20:57 - ',
 '4/8/24, 20:57 - ',
 '4/8/24, 20:58 - ',
 '4/8/24, 20:58 - ',
 '4/8/24, 20:58 - ',
 '4/8/24, 20:58 - ',
 '4/8/24, 20:58 - ',
 '4/8/24, 20:59 - ',
 '4/8/24, 20:59 - ',
 '4/8/24, 20:59 - ',
 '4/8/24, 20:59 - ',
 '4/8/24, 20:59 - ',
 '4/8/24, 21:02 - ',
 '4/8/24, 21:03 - ',
 '4/8/24, 21:05 - ',
 '4/8/24, 21:06 - ',
 '4/8/24, 21:06 - ',
 '4/8/24, 21:07 - ',
 '4/8/24, 21:08 - ',
 '4/8/24, 21:08 - ',
 '4/8/24, 21:08 - ',
 '4/8/24, 21:08 - ',
 '4/8/24, 21:08 - ',
 '4/8/24, 21:08 - ',
 '4/8/24, 21:08 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:09 - ',
 '4/8/24, 21:10 - ',
 '4/8/24, 21:10 - ',
 '4/8/24, 21:10 - ',
 '4/8/24, 21:15 - ',
 '4/8/24, 21:16 - ',
 '4/8/24, 21:16 - ',
 '4/8/24, 21:16 - ',
 '4/8/24, 21:18 - ',
 '4/8/24, 21:18 - ',
 '4/8/24, 21:18 - ',
 '4/8/24, 21:20 - ',
 '4/8/24, 21:21 - ',
 '4/8/24, 21:21 - ',
 '4/8/24, 21:21 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:22 - ',
 '4/8/24, 21:23 - ',
 '4/8/24, 21:23 - ',
 '4/8/24, 21:23 - ',
 '4/8/24, 21:24 - ',
 '4/8/24, 21:24 - ',
 '4/8/24, 21:24 - ',
 '4/8/24, 21:25 - ',
 '4/8/24, 21:25 - ',
 '4/8/24, 21:25 - ',
 '4/8/24, 21:26 - ',
 '4/8/24, 21:26 - ',
 '4/8/24, 21:26 - ',
 '4/8/24, 21:26 - ',
 '4/8/24, 21:27 - ',
 '4/8/24, 21:28 - ',
 '4/8/24, 21:28 - ',
 '4/8/24, 21:28 - ',
 '4/8/24, 21:30 - ',
 '4/9/24, 13:31 - ',
 '4/9/24, 13:37 - ',
 '4/11/24, 19:32 - ',
 '4/11/24, 20:33 - ',
 '4/11/24, 20:33 - ',
 '4/11/24, 20:42 - ',
 '4/11/24, 20:42 - ',
 '4/13/24, 18:27 - ',
 '4/13/24, 18:45 - ',
 '4/13/24, 19:39 - ',
 '4/14/24, 07:30 - ',
 '4/14/24, 07:49 - ',
 '4/14/24, 07:50 - ',
 '4/14/24, 07:52 - ',
 '4/14/24, 08:28 - ',
 '4/14/24, 09:08 - ',
 '4/14/24, 10:07 - ',
 '4/14/24, 11:06 - ',
 '4/15/24, 21:11 - ',
 '4/16/24, 19:29 - ',
 '4/16/24, 19:57 - ',
 '4/16/24, 20:06 - ',
 '4/17/24, 14:18 - ',
 '4/17/24, 19:29 - ',
 '4/17/24, 20:03 - ',
 '4/18/24, 00:39 - ',
 '4/18/24, 00:39 - ',
 '4/18/24, 05:51 - ',
 '4/18/24, 06:03 - ',
 '4/18/24, 06:03 - ',
 '4/18/24, 06:04 - ',
 '4/18/24, 06:04 - ',
 '4/18/24, 06:04 - ',
 '4/18/24, 06:04 - ',
 '4/18/24, 06:04 - ',
 '4/18/24, 10:24 - ',
 '4/18/24, 19:55 - ',
 '4/18/24, 19:57 - ',
 '4/18/24, 19:59 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:00 - ',
 '4/18/24, 20:01 - ',
 '4/18/24, 20:01 - ',
 '4/18/24, 20:01 - ',
 '4/18/24, 20:01 - ',
 '4/18/24, 20:01 - ',
 '4/18/24, 20:01 - ',
 '4/18/24, 20:01 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:02 - ',
 '4/18/24, 20:03 - ',
 '4/18/24, 20:03 - ',
 '4/18/24, 20:03 - ',
 '4/18/24, 20:06 - ',
 '4/18/24, 20:14 - ',
 '4/18/24, 20:20 - ',
 '4/18/24, 20:20 - ',
 '4/18/24, 20:20 - ',
 '4/18/24, 20:21 - ',
 '4/18/24, 21:00 - ',
 '4/18/24, 21:03 - ',
 '4/18/24, 21:00 - ',
 '4/19/24, 00:40 - ',
 '4/19/24, 00:40 - ',
 '4/19/24, 00:41 - ',
 '4/19/24, 00:41 - ',
 '4/19/24, 00:41 - ',
 '4/19/24, 00:41 - ',
 '4/19/24, 00:42 - ',
 '4/19/24, 00:43 - ',
 '4/19/24, 00:43 - ',
 '4/19/24, 09:46 - ',
 '4/19/24, 09:46 - ',
 '4/19/24, 09:48 - ',
 '4/19/24, 09:48 - ',
 '4/19/24, 12:13 - ',
 '4/19/24, 12:13 - ',
 '4/19/24, 12:22 - ',
 '4/19/24, 12:22 - ',
 '4/19/24, 18:07 - ',
 '4/19/24, 18:16 - ',
 '4/19/24, 20:15 - ',
 '4/20/24, 10:59 - ',
 '4/21/24, 17:53 - ',
 '4/22/24, 13:59 - ',
 '4/22/24, 18:17 - ',
 '4/24/24, 21:07 - ',
 '4/25/24, 19:29 - ',
 '4/25/24, 19:37 - ',
 '4/25/24, 19:38 - ',
 '4/25/24, 20:23 - ',
 '4/25/24, 20:47 - ',
 '4/28/24, 17:59 - ',
 '4/29/24, 11:29 - ',
 '4/29/24, 11:30 - ',
 '4/29/24, 11:30 - ',
 '4/29/24, 20:10 - ',
 '5/1/24, 15:50 - ',
 '5/2/24, 18:09 - ',
 '5/3/24, 18:56 - ',
 '5/4/24, 10:55 - ',
 '5/7/24, 11:13 - ',
 '5/7/24, 11:13 - ',
 '5/7/24, 11:13 - ',
 '5/7/24, 11:13 - ',
 '5/7/24, 11:14 - ',
 '5/7/24, 11:15 - ',
 '5/7/24, 11:24 - ',
 '5/7/24, 11:24 - ',
 '5/7/24, 11:27 - ',
 '5/7/24, 11:27 - ',
 '5/7/24, 11:33 - ',
 '5/7/24, 11:33 - ',
 '5/7/24, 11:33 - ',
 '5/7/24, 11:33 - ',
 '5/7/24, 11:33 - ',
 '5/7/24, 11:33 - ',
 '5/7/24, 11:33 - ',
 '5/7/24, 11:34 - ',
 '5/7/24, 11:34 - ',
 '5/7/24, 11:34 - ',
 '5/7/24, 11:34 - ',
 '5/7/24, 11:40 - ',
 '5/7/24, 11:40 - ',
 '5/7/24, 11:40 - ',
 '5/7/24, 11:46 - ',
 '5/7/24, 11:46 - ',
 '5/7/24, 11:48 - ',
 '5/7/24, 11:49 - ',
 '5/7/24, 11:49 - ',
 '5/7/24, 11:51 - ',
 '5/7/24, 11:51 - ',
 '5/7/24, 11:53 - ',
 '5/7/24, 19:33 - ',
 '5/7/24, 19:40 - ',
 '5/7/24, 20:29 - ',
 '5/8/24, 19:26 - ',
 '5/8/24, 19:32 - ',
 '5/9/24, 18:46 - ',
 '5/9/24, 19:07 - ',
 '5/11/24, 16:17 - ',
 '5/11/24, 16:19 - ',
 '5/11/24, 17:00 - ',
 '5/11/24, 17:00 - ',
 '5/11/24, 17:00 - ',
 '5/11/24, 17:01 - ',
 '5/11/24, 18:43 - ',
 '5/12/24, 18:18 - ',
 '5/12/24, 18:56 - ',
 '5/12/24, 18:56 - ',
 '5/12/24, 18:57 - ',
 '5/12/24, 18:57 - ',
 '5/12/24, 18:57 - ',
 '5/12/24, 18:57 - ',
 '5/12/24, 18:58 - ',
 '5/12/24, 18:58 - ',
 '5/12/24, 18:59 - ',
 '5/15/24, 08:13 - ',
 '5/15/24, 08:13 - ',
 '5/15/24, 09:00 - ',
 '5/15/24, 10:40 - ',
 '5/15/24, 10:41 - ',
 '5/15/24, 10:42 - ',
 '5/15/24, 10:42 - ',
 '5/15/24, 10:45 - ',
 '5/15/24, 11:06 - ',
 '5/15/24, 11:06 - ',
 '5/15/24, 11:06 - ',
 '5/15/24, 11:13 - ',
 '5/15/24, 18:50 - ',
 '5/15/24, 19:03 - ',
 '5/19/24, 18:56 - ',
 '5/24/24, 19:36 - ',
 '5/24/24, 19:40 - ',
 '5/24/24, 19:40 - ',
 '5/28/24, 19:31 - ',
 '5/29/24, 13:40 - ',
 '5/29/24, 13:41 - ',
 '5/29/24, 13:41 - ',
 '5/29/24, 13:41 - ',
 '5/29/24, 13:41 - ',
 '5/29/24, 13:41 - ',
 '5/29/24, 13:56 - ',
 '5/29/24, 13:57 - ',
 '5/29/24, 13:57 - ',
 '5/29/24, 13:57 - ',
 '5/29/24, 13:57 - ',
 '5/29/24, 13:58 - ',
 '5/29/24, 13:58 - ',
 '5/29/24, 13:59 - ',
 '5/29/24, 14:13 - ',
 '5/29/24, 15:30 - ',
 '5/29/24, 15:32 - ',
 '5/29/24, 15:53 - ',
 '5/29/24, 18:11 - ',
 '5/29/24, 18:20 - ',
 '5/29/24, 18:20 - ',
 '5/29/24, 18:21 - ',
 '5/29/24, 18:21 - ',
 '5/29/24, 18:21 - ',
 '5/29/24, 18:21 - ',
 '5/29/24, 18:18 - ',
 '5/29/24, 18:40 - ',
 '5/29/24, 18:40 - ',
 '5/29/24, 18:45 - ',
 '5/29/24, 18:45 - ',
 '5/29/24, 18:46 - ',
 '5/29/24, 18:49 - ',
 '5/29/24, 18:53 - ',
 '5/29/24, 18:53 - ',
 '5/29/24, 18:53 - ',
 '5/29/24, 19:45 - ',
 '5/29/24, 19:46 - ',
 '5/29/24, 19:46 - ',
 '5/29/24, 19:46 - ',
 '5/29/24, 19:46 - ',
 '5/29/24, 19:47 - ',
 '5/29/24, 20:00 - ',
 '5/29/24, 20:00 - ',
 '5/29/24, 21:15 - ',
 '5/29/24, 23:22 - ',
 '5/29/24, 23:22 - ',
 '5/29/24, 23:24 - ',
 '5/29/24, 23:24 - ',
 '5/29/24, 23:24 - ',
 '5/29/24, 23:24 - ',
 '5/29/24, 23:25 - ',
 '5/29/24, 23:25 - ',
 '5/29/24, 23:25 - ',
 '5/29/24, 23:25 - ',
 '5/29/24, 23:26 - ',
 '5/29/24, 23:27 - ',
 '5/29/24, 23:27 - ',
 '5/29/24, 23:28 - ',
 '5/29/24, 23:30 - ',
 '5/29/24, 23:30 - ',
 '5/29/24, 23:31 - ',
 '5/29/24, 23:31 - ',
 '5/29/24, 23:31 - ',
 '5/29/24, 23:31 - ',
 '5/29/24, 23:32 - ',
 '5/29/24, 23:32 - ',
 '5/29/24, 23:33 - ',
 '5/29/24, 23:33 - ',
 '5/29/24, 23:37 - ',
 '5/29/24, 23:37 - ',
 '5/29/24, 23:38 - ',
 '5/29/24, 23:40 - ',
 '5/30/24, 19:55 - ',
 '5/31/24, 20:34 - ',
 '5/31/24, 20:36 - ',
 '6/1/24, 09:53 - ',
 '6/1/24, 09:53 - ',
 '6/1/24, 09:53 - ',
 '6/1/24, 09:54 - ',
 '6/1/24, 09:54 - ',
 '6/1/24, 09:54 - ',
 '6/1/24, 10:15 - ',
 '6/1/24, 10:31 - ',
 '6/1/24, 10:31 - ',
 '6/1/24, 10:35 - ',
 '6/1/24, 10:50 - ',
 '6/1/24, 10:52 - ',
 '6/1/24, 10:53 - ',
 '6/1/24, 10:59 - ',
 '6/1/24, 12:57 - ',
 '6/1/24, 13:01 - ',
 '6/1/24, 13:01 - ',
 '6/1/24, 13:01 - ',
 '6/1/24, 13:02 - ',
 '6/1/24, 13:02 - ',
 '6/1/24, 13:02 - ',
 '6/1/24, 13:02 - ',
 '6/1/24, 13:02 - ',
 '6/1/24, 13:03 - ',
 '6/1/24, 13:03 - ',
 '6/1/24, 13:03 - ',
 '6/1/24, 13:04 - ',
 '6/1/24, 13:05 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:39 - ',
 '6/1/24, 23:40 - ',
 '6/1/24, 23:40 - ',
 '6/1/24, 23:40 - ',
 '6/1/24, 23:40 - ',
 '6/1/24, 23:40 - ',
 '6/1/24, 23:40 - ',
 '6/1/24, 23:40 - ',
 '6/1/24, 23:41 - ',
 '6/1/24, 23:41 - ',
 '6/1/24, 23:53 - ',
 '6/2/24, 09:08 - ',
 '6/2/24, 09:08 - ',
 '6/2/24, 09:08 - ',
 '6/2/24, 09:22 - ',
 '6/2/24, 09:22 - ',
 '6/2/24, 10:33 - ',
 '6/2/24, 10:33 - ',
 '6/2/24, 10:33 - ',
 '6/2/24, 10:39 - ',
 '6/2/24, 10:39 - ',
 '6/2/24, 10:40 - ',
 '6/2/24, 10:41 - ',
 '6/2/24, 10:41 - ',
 '6/2/24, 10:41 - ',
 '6/2/24, 10:41 - ',
 '6/2/24, 10:42 - ',
 '6/2/24, 10:42 - ',
 '6/2/24, 10:42 - ',
 '6/2/24, 10:42 - ',
 '6/2/24, 10:42 - ',
 '6/2/24, 10:42 - ',
 '6/2/24, 10:42 - ',
 '6/2/24, 10:43 - ',
 '6/2/24, 10:43 - ',
 '6/2/24, 10:43 - ',
 '6/2/24, 10:43 - ',
 '6/2/24, 10:43 - ',
 '6/2/24, 10:44 - ',
 '6/2/24, 10:44 - ',
 '6/2/24, 10:44 - ',
 '6/2/24, 10:44 - ',
 '6/2/24, 10:44 - ',
 '6/2/24, 10:45 - ',
 '6/2/24, 10:45 - ',
 '6/2/24, 10:45 - ',
 '6/2/24, 10:46 - ',
 '6/2/24, 10:46 - ',
 '6/2/24, 10:46 - ',
 '6/2/24, 10:47 - ',
 '6/2/24, 10:47 - ',
 '6/2/24, 10:47 - ',
 '6/2/24, 10:47 - ',
 '6/2/24, 10:48 - ',
 '6/2/24, 10:48 - ',
 '6/2/24, 10:49 - ',
 '6/2/24, 11:39 - ',
 '6/2/24, 11:39 - ',
 '6/2/24, 11:40 - ',
 '6/2/24, 11:40 - ',
 '6/2/24, 11:40 - ',
 '6/2/24, 11:41 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:07 - ',
 '6/2/24, 12:08 - ',
 '6/2/24, 12:08 - ',
 '6/2/24, 12:08 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:09 - ',
 '6/2/24, 12:10 - ',
 '6/2/24, 12:10 - ',
 '6/2/24, 12:10 - ',
 '6/2/24, 12:10 - ',
 '6/2/24, 12:10 - ',
 '6/2/24, 12:11 - ',
 '6/2/24, 12:11 - ',
 '6/2/24, 12:11 - ',
 '6/2/24, 12:11 - ',
 '6/2/24, 12:11 - ',
 '6/2/24, 12:11 - ',
 '6/2/24, 12:11 - ',
 '6/2/24, 12:12 - ',
 '6/2/24, 12:13 - ',
 '6/2/24, 12:13 - ',
 '6/2/24, 12:13 - ',
 '6/2/24, 12:13 - ',
 '6/2/24, 12:13 - ',
 '6/2/24, 12:14 - ',
 '6/2/24, 12:14 - ',
 '6/2/24, 12:14 - ',
 '6/2/24, 12:14 - ',
 '6/2/24, 12:14 - ',
 '6/2/24, 12:16 - ',
 '6/2/24, 12:16 - ',
 '6/2/24, 12:16 - ',
 '6/2/24, 12:16 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:17 - ',
 '6/2/24, 12:18 - ',
 '6/2/24, 12:18 - ',
 '6/2/24, 12:18 - ',
 '6/2/24, 12:19 - ',
 '6/2/24, 12:19 - ',
 '6/2/24, 12:19 - ',
 '6/2/24, 12:19 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:20 - ',
 '6/2/24, 12:25 - ',
 '6/2/24, 12:25 - ',
 '6/2/24, 12:26 - ',
 '6/2/24, 12:26 - ',
 '6/2/24, 12:26 - ',

In [25]:
df = pd.DataFrame({'user_message' : messages, 'message_date' : dates})
# convert message_date type
df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %H:%M - ')

df.rename(columns={'message_date': 'date'}, inplace=True)
df.head()

                                   user_message                date
0                                     Pawan: \n 2024-03-30 18:16:00
1  Diksha Joshi: Guys m apne new ghr m gye hu\n 2024-03-30 18:18:00
2                           Diksha Joshi: 😂😂😂\n 2024-03-30 18:18:00
3      Diksha Joshi: To ma kuch bole ni pa re\n 2024-03-30 18:18:00
4     Diksha Joshi: Wrna m bhut bolne k mne h\n 2024-03-30 18:18:00

In [26]:
df.shape

(7211, 2)

In [ ]:
# seprate users and messages
users = []
messages = []

for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s',message)
    if entry[1:]:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace = True)

                 date          user                         message
0 2024-03-30 18:16:00         Pawan                              \n
1 2024-03-30 18:18:00  Diksha Joshi  Guys m apne new ghr m gye hu\n
2 2024-03-30 18:18:00  Diksha Joshi                           😂😂😂\n
3 2024-03-30 18:18:00  Diksha Joshi      To ma kuch bole ni pa re\n
4 2024-03-30 18:18:00  Diksha Joshi     Wrna m bhut bolne k mne h\n

In [28]:
df.sample(5)

                    date          user                          message
4433 2025-03-13 12:03:00         Kiran                        Hemlata\n
1044 2024-06-02 15:04:00     (Chandan)                <Media omitted>\n
3938 2025-02-01 17:09:00   Piyush Ñegi                aaya ha ya nahi\n
255  2024-04-06 14:25:00  Diksha Joshi  Ham to Nash nash se rubaru ha\n
4886 2025-06-02 21:09:00  Gaurav Joshi                      Datesheet\n

In [31]:
df['year'] = df['date'].dt.year

In [33]:
df.sample(10)

,date,user,message,year
854,2024-06-02 12:07:00,Pawan,Mere jaan nikal re h\n,2024
6086,2025-09-03 21:16:00,(Chandan),Jana chahiye\n,2025
1456,2024-07-04 08:27:00,Pawan,Oe sale to kaha gum ho gaya aajkal\n,2024
1966,2024-07-13 10:50:00,Kiran,Tumhara ho to gya Moye moye\n,2024
1462,2024-07-04 08:29:00,Pawan,Kuch b\n,2024
5759,2025-08-19 20:29:00,Kiran,Best h bhai\n,2025
3802,2025-01-17 09:38:00,Ritesh,Yaha link se accha ek insta pee he ek group ba...,2025
917,2024-06-02 12:19:00,Diksha Joshi,Pawan khna bhi ni khra bhl\n,2024
5020,2025-07-30 20:50:00,Pawan,Agle semester pakka aa jaunga\n,2025
865,2024-06-02 12:09:00,(Chandan),Vo mehul sir ki drive mai chle gye hai yrr\n,2024

In [36]:
df['month'] = df['date'].dt.month_name()

In [37]:
df.sample(10)

,date,user,message,year,month
1069,2024-06-02 15:06:00,(Chandan),<Media omitted>\n,2024,June
845,2024-06-02 10:48:00,Pawan,Hm aab theek h ......par vo chai kam or coffe...,2024,June
872,2024-06-02 12:09:00,Pawan,Chandu bhai\n,2024,June
3955,2025-02-01 19:58:00,Diksha Joshi,😂😂\n,2025,February
1074,2024-06-03 13:54:00,Diksha Joshi,Kr do phir\n,2024,June
2462,2024-10-22 11:19:00,Diksha Joshi,Ha Bhai btao\n,2024,October
6526,2025-09-12 20:11:00,Ritesh,Oho wo tho ata he naui hamai se kisi ko 😭\n,2025,September
4598,2025-03-22 08:01:00,Gaurav Joshi,Thankyou diksha mam 😂\n,2025,March
636,2024-05-07 11:51:00,Diksha Joshi,Kezusel h\n,2024,May
3554,2024-12-25 09:22:00,Piyush Ñegi,<Media omitted>\n,2024,December

In [38]:
df['day'] = df['date'].dt.day

In [39]:
df.sample(10)

,date,user,message,year,month,day
4751,2025-03-26 20:18:00,Diksha Joshi,<Media omitted>\n,2025,March,26
4239,2025-03-13 08:41:00,Diksha Joshi,Haa\n,2025,March,13
6612,2025-09-18 08:52:00,Diksha Joshi,To 2.30 se thik ha??\n,2025,September,18
4519,2025-03-16 19:47:00,(Chandan),https://www.instagram.com/reel/DHNfogLM6Ve/?ig...,2025,March,16
6946,2025-10-20 09:02:00,Ritesh,guys Diwali tho kal hai\n,2025,October,20
6966,2025-10-20 09:13:00,Ritesh,aisa name maat loo\n,2025,October,20
6988,2025-10-20 09:18:00,Diksha Joshi,Wowww\n,2025,October,20
6402,2025-09-09 19:20:00,Diksha Joshi,Best🌝\n,2025,September,9
6959,2025-10-20 09:12:00,Ritesh,jis jis ke waha kaju katlii ayi hai pahle he b...,2025,October,20
6819,2025-09-18 17:17:00,(Chandan),<Media omitted>\n,2025,September,18

In [40]:
df['hour'] = df['date'].dt.hour
df['min'] = df['date'].dt.minute

In [41]:
df.sample(10)

,date,user,message,year,month,day,hour,min
1191,2024-06-13 21:09:00,Nirjala,Vhi\n,2024,June,13,21,9
336,2024-04-06 14:42:00,Gaurav Joshi,Bhai yrr asa kux nhi hai yrr kaha me lower mid...,2024,April,6,14,42
4993,2025-07-29 16:32:00,Piyush Ñegi,Iss baar pehle se bhe bdiya khana milega\n,2025,July,29,16,32
3739,2025-01-06 23:48:00,Gaurav Joshi,https://www.instagram.com/reel/DEeTl4US3T2/?ig...,2025,January,6,23,48
3868,2025-01-25 20:42:00,Pawan,<Media omitted>\n,2025,January,25,20,42
5084,2025-07-31 11:30:00,Piyush Ñegi,Ha\n,2025,July,31,11,30
4683,2025-03-24 21:14:00,Piyush Ñegi,<Media omitted>\n,2025,March,24,21,14
4541,2025-03-17 15:45:00,Gaurav Joshi,https://www.instagram.com/reel/DHNhdH8BIMz/?ig...,2025,March,17,15,45
2755,2024-10-31 08:57:00,Diksha Joshi,Dadu\n,2024,October,31,8,57
4253,2025-03-13 08:42:00,Kiran,Vo yha ni h y\n,2025,March,13,8,42